title: My Resume | Fahien
description: This is my curriculum vitae
url: 'http://fahien.me'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Antonio Caggiano
tagline: Game Developer
pic: profile2.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: infoantoniocaggiano@gmail.com
phone: +39 348 059 8485
website: fahien.me #do not add http://
linkedin: antoniocaggiano
github: Fahien
twitter: '@Fahien'
facebook: Fahien

# Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-68855324-1

#Update all the sections by editing the files inside _includes folder.
