title: My Resume | Fahien
description: This is my curriculum vitae
url: 'https://www.antoniocaggiano.eu'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Antonio Caggiano
tagline: Software Engineer
pic: profile2.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: info@antoniocaggiano.eu
phone: +39 348 059 8485
website: antoniocaggiano.eu #do not add http://
linkedin: antoniocaggiano
github: Fahien
twitter: '@Fahien'
facebook: Fahien

#Update all the sections by editing the files inside _includes folder.
